In [3]:
import pandas as pd
tabla_principal = 'join.csv'
tabla_foranea = 'foreign.csv'
tabla_orden = 'columns.csv'

tabla1 = pd.read_csv(tabla_principal)
foranea = pd.read_csv(tabla_foranea)
columnas = pd.read_csv(tabla_orden)
tabla2 = tabla1.merge(foranea, how="left", on=["NOM_CAMP","NOM_TABLA"], )
tabla3 = tabla2.merge(columnas[['NOM_CAMP','NOM_TABLA',O]],how="left",on=["NOM_CAMP","NOM_TABLA"], )
tabla3

,NOM_TABLA,NOM_CAMP,TIPO,TAMAÑO,CLAVE,FOR_TABLA,TABLE_CATALOG,TABLE_SCHEMA,ORDINAL_POSITION,COLUMN_DEFAULT,...,DATETIME_PRECISION,CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_TYPE,COLUMN_KEY,EXTRA,PRIVILEGES,COLUMN_COMMENT,GENERATION_EXPRESSION,SRS_ID
0,banjercito,id,INT,NaN,principal,NaN,def,sniiv,1.0,NaN,...,NaN,NaN,NaN,int unsigned,PRI,NaN,"select,insert,update,references",NaN,NaN,NaN
1,banjercito,clave_entidad_federativa,CHAR,2,Foranea,c_entidad_federativa,def,sniiv,2.0,NaN,...,NaN,utf8,utf8_spanish_ci,char(2),MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
2,banjercito,clave_municipio,CHAR,3,Foranea,NaN,def,sniiv,3.0,NaN,...,NaN,utf8,utf8_spanish_ci,char(3),NaN,NaN,"select,insert,update,references",NaN,NaN,NaN
3,banjercito,id_linea_credito,INT,NaN,Foranea,c_linea_credito_banjercito,def,sniiv,4.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
4,banjercito,producto,ENUM,NaN,Interna,NaN,def,sniiv,5.0,NaN,...,NaN,utf8,utf8_spanish_ci,"enum('Crédito hipotecario','Crédito liquidez')",NaN,NaN,"select,insert,update,references",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,subprograma_fovissste,id_esquema,INT,NaN,foranea,c_esquema_fovissste,def,sniiv,2.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
1091,subprograma_fovissste,id_linea_credito,INT,NaN,foranea,c_linea_credito_fovissste,def,sniiv,3.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
1092,subprograma_fovissste,id_modalidad,INT,NaN,Foranea,c_modalidad_fovissste,def,sniiv,4.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
1093,subprograma_fovissste,id_subprograma,INT,NaN,foranea,c_subprograma,def,sniiv,5.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN
1094,subprograma_fovissste,id_tipo_credito,INT,NaN,foranea,c_tipo_credito,def,sniiv,6.0,NaN,...,NaN,NaN,NaN,int unsigned,MUL,NaN,"select,insert,update,references",NaN,NaN,NaN